export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'projects',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-2.svg'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: true,
};

export const homeObjThree = {
    id: 'unknown',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false,
};